version: '3.4'

services:
  postgresql:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-db
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  postgresql-test:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: my-test-db
    ports:
      - '5433:5432'

  redis:
    image: redis:7.2.3
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  redis-queue:
    image: redis:7.2.3
    ports:
      - '6380:6379'
    expose:
      - '6380'
    volumes:
      - redis:/data

  redis-test:
    image: redis:7.2.3
    ports:
      - '6381:6379'

volumes:
  redis:
  redis-queue:
