name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - '**'

    
jobs:
  check-format-build:
    name: Check, Format & Build
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install project deps
        run: yarn --prefer-offline

      - name: Check format
        run: make check-format

      - name: Build
        run: make build